//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for address-exclusionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="address-exclusionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="inet-address" type="{urn:jboss:domain:1.4}inet-addressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loopback" type="{urn:jboss:domain:1.4}loopbackType"/>
 *         &lt;element name="loopback-address" type="{urn:jboss:domain:1.4}loopback-addressType"/>
 *         &lt;element name="multicast" type="{urn:jboss:domain:1.4}multicastType"/>
 *         &lt;element name="point-to-point" type="{urn:jboss:domain:1.4}point-to-pointType"/>
 *         &lt;element name="virtual" type="{urn:jboss:domain:1.4}interface-virtualType"/>
 *         &lt;element name="up" type="{urn:jboss:domain:1.4}interface-upType"/>
 *         &lt;element name="public-address" type="{urn:jboss:domain:1.4}public-addressType"/>
 *         &lt;element name="link-local-address" type="{urn:jboss:domain:1.4}link-local-addressType"/>
 *         &lt;element name="site-local-address" type="{urn:jboss:domain:1.4}site-local-addressType"/>
 *         &lt;element name="nic" type="{urn:jboss:domain:1.4}nicType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nic-match" type="{urn:jboss:domain:1.4}nic-matchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subnet-match" type="{urn:jboss:domain:1.4}subnet-matchType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "address-exclusionType", propOrder = {
    "inetAddress",
    "loopback",
    "loopbackAddress",
    "multicast",
    "pointToPoint",
    "virtual",
    "up",
    "publicAddress",
    "linkLocalAddress",
    "siteLocalAddress",
    "nic",
    "nicMatch",
    "subnetMatch"
})
public class AddressExclusionType {

    @XmlElement(name = "inet-address")
    protected List<InetAddressType> inetAddress;
    protected LoopbackType loopback;
    @XmlElement(name = "loopback-address")
    protected LoopbackAddressType loopbackAddress;
    protected MulticastType multicast;
    @XmlElement(name = "point-to-point")
    protected PointToPointType pointToPoint;
    protected InterfaceVirtualType virtual;
    protected InterfaceUpType up;
    @XmlElement(name = "public-address")
    protected PublicAddressType publicAddress;
    @XmlElement(name = "link-local-address")
    protected LinkLocalAddressType linkLocalAddress;
    @XmlElement(name = "site-local-address")
    protected SiteLocalAddressType siteLocalAddress;
    protected List<NicType> nic;
    @XmlElement(name = "nic-match")
    protected List<NicMatchType> nicMatch;
    @XmlElement(name = "subnet-match")
    protected List<SubnetMatchType> subnetMatch;

    /**
     * Gets the value of the inetAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inetAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInetAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InetAddressType }
     * 
     * 
     */
    public List<InetAddressType> getInetAddress() {
        if (inetAddress == null) {
            inetAddress = new ArrayList<InetAddressType>();
        }
        return this.inetAddress;
    }

    /**
     * Gets the value of the loopback property.
     * 
     * @return
     *     possible object is
     *     {@link LoopbackType }
     *     
     */
    public LoopbackType getLoopback() {
        return loopback;
    }

    /**
     * Sets the value of the loopback property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoopbackType }
     *     
     */
    public void setLoopback(LoopbackType value) {
        this.loopback = value;
    }

    /**
     * Gets the value of the loopbackAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LoopbackAddressType }
     *     
     */
    public LoopbackAddressType getLoopbackAddress() {
        return loopbackAddress;
    }

    /**
     * Sets the value of the loopbackAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoopbackAddressType }
     *     
     */
    public void setLoopbackAddress(LoopbackAddressType value) {
        this.loopbackAddress = value;
    }

    /**
     * Gets the value of the multicast property.
     * 
     * @return
     *     possible object is
     *     {@link MulticastType }
     *     
     */
    public MulticastType getMulticast() {
        return multicast;
    }

    /**
     * Sets the value of the multicast property.
     * 
     * @param value
     *     allowed object is
     *     {@link MulticastType }
     *     
     */
    public void setMulticast(MulticastType value) {
        this.multicast = value;
    }

    /**
     * Gets the value of the pointToPoint property.
     * 
     * @return
     *     possible object is
     *     {@link PointToPointType }
     *     
     */
    public PointToPointType getPointToPoint() {
        return pointToPoint;
    }

    /**
     * Sets the value of the pointToPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointToPointType }
     *     
     */
    public void setPointToPoint(PointToPointType value) {
        this.pointToPoint = value;
    }

    /**
     * Gets the value of the virtual property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceVirtualType }
     *     
     */
    public InterfaceVirtualType getVirtual() {
        return virtual;
    }

    /**
     * Sets the value of the virtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceVirtualType }
     *     
     */
    public void setVirtual(InterfaceVirtualType value) {
        this.virtual = value;
    }

    /**
     * Gets the value of the up property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceUpType }
     *     
     */
    public InterfaceUpType getUp() {
        return up;
    }

    /**
     * Sets the value of the up property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceUpType }
     *     
     */
    public void setUp(InterfaceUpType value) {
        this.up = value;
    }

    /**
     * Gets the value of the publicAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PublicAddressType }
     *     
     */
    public PublicAddressType getPublicAddress() {
        return publicAddress;
    }

    /**
     * Sets the value of the publicAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicAddressType }
     *     
     */
    public void setPublicAddress(PublicAddressType value) {
        this.publicAddress = value;
    }

    /**
     * Gets the value of the linkLocalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LinkLocalAddressType }
     *     
     */
    public LinkLocalAddressType getLinkLocalAddress() {
        return linkLocalAddress;
    }

    /**
     * Sets the value of the linkLocalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkLocalAddressType }
     *     
     */
    public void setLinkLocalAddress(LinkLocalAddressType value) {
        this.linkLocalAddress = value;
    }

    /**
     * Gets the value of the siteLocalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SiteLocalAddressType }
     *     
     */
    public SiteLocalAddressType getSiteLocalAddress() {
        return siteLocalAddress;
    }

    /**
     * Sets the value of the siteLocalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteLocalAddressType }
     *     
     */
    public void setSiteLocalAddress(SiteLocalAddressType value) {
        this.siteLocalAddress = value;
    }

    /**
     * Gets the value of the nic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NicType }
     * 
     * 
     */
    public List<NicType> getNic() {
        if (nic == null) {
            nic = new ArrayList<NicType>();
        }
        return this.nic;
    }

    /**
     * Gets the value of the nicMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nicMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNicMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NicMatchType }
     * 
     * 
     */
    public List<NicMatchType> getNicMatch() {
        if (nicMatch == null) {
            nicMatch = new ArrayList<NicMatchType>();
        }
        return this.nicMatch;
    }

    /**
     * Gets the value of the subnetMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subnetMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubnetMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubnetMatchType }
     * 
     * 
     */
    public List<SubnetMatchType> getSubnetMatch() {
        if (subnetMatch == null) {
            subnetMatch = new ArrayList<SubnetMatchType>();
        }
        return this.subnetMatch;
    }

}
