//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Empty element indicating that sockets using this interface
 *                 should be bound to a wildcard address. The IPv6 wildcard
 *                 address (::) will be used unless the java.net.preferIpV4Stack
 *                 system property is set to true, in which case the IPv4
 *                 wildcard address (0.0.0.0) will be used. If a socket is
 *                 bound to an IPv6 anylocal address on a dual-stack machine,
 *                 it can accept both IPv6 and IPv4 traffic; if it is bound to
 *                 an IPv4 (IPv4-mapped) anylocal address, it can only accept
 *                 IPv4 traffic.
 *             
 * 
 * <p>Java class for any-addressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="any-addressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "any-addressType")
public class AnyAddressType {


}
