//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of the server side authentication mechanisms.
 * 
 *                 Optionally one truststore can be defined and one username/password based store can be defined.
 *                 Authentication will first attempt to use the truststore and if this is not available will fall back
 *                 to the username/password authentication.
 * 
 *                 If none of these are specified the only available mechanism will be the local mechanism for the
 *                 Native interface and the HTTP interface will not be accessible.
 *             
 * 
 * <p>Java class for authenticationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="truststore" type="{urn:jboss:domain:1.4}keyStoreType" minOccurs="0"/>
 *         &lt;element name="local" type="{urn:jboss:domain:1.4}localType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="jaas" type="{urn:jboss:domain:1.4}jaasAuthenticationType" minOccurs="0"/>
 *           &lt;element name="ldap" type="{urn:jboss:domain:1.4}ldapAuthenticationType" minOccurs="0"/>
 *           &lt;element name="properties" type="{urn:jboss:domain:1.4}propertiesAuthenticationType" minOccurs="0"/>
 *           &lt;element name="users" type="{urn:jboss:domain:1.4}usersAuthenticationType" minOccurs="0"/>
 *           &lt;element name="plug-in" type="{urn:jboss:domain:1.4}plug-inAuthType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticationType", propOrder = {
    "truststore",
    "local",
    "jaas",
    "ldap",
    "properties",
    "users",
    "plugIn"
})
public class AuthenticationType {

    protected KeyStoreType truststore;
    protected LocalType local;
    protected JaasAuthenticationType jaas;
    protected LdapAuthenticationType ldap;
    protected PropertiesAuthenticationType properties;
    protected UsersAuthenticationType users;
    @XmlElement(name = "plug-in")
    protected PlugInAuthType plugIn;

    /**
     * Gets the value of the truststore property.
     * 
     * @return
     *     possible object is
     *     {@link KeyStoreType }
     *     
     */
    public KeyStoreType getTruststore() {
        return truststore;
    }

    /**
     * Sets the value of the truststore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyStoreType }
     *     
     */
    public void setTruststore(KeyStoreType value) {
        this.truststore = value;
    }

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link LocalType }
     *     
     */
    public LocalType getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalType }
     *     
     */
    public void setLocal(LocalType value) {
        this.local = value;
    }

    /**
     * Gets the value of the jaas property.
     * 
     * @return
     *     possible object is
     *     {@link JaasAuthenticationType }
     *     
     */
    public JaasAuthenticationType getJaas() {
        return jaas;
    }

    /**
     * Sets the value of the jaas property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaasAuthenticationType }
     *     
     */
    public void setJaas(JaasAuthenticationType value) {
        this.jaas = value;
    }

    /**
     * Gets the value of the ldap property.
     * 
     * @return
     *     possible object is
     *     {@link LdapAuthenticationType }
     *     
     */
    public LdapAuthenticationType getLdap() {
        return ldap;
    }

    /**
     * Sets the value of the ldap property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapAuthenticationType }
     *     
     */
    public void setLdap(LdapAuthenticationType value) {
        this.ldap = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesAuthenticationType }
     *     
     */
    public PropertiesAuthenticationType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesAuthenticationType }
     *     
     */
    public void setProperties(PropertiesAuthenticationType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersAuthenticationType }
     *     
     */
    public UsersAuthenticationType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersAuthenticationType }
     *     
     */
    public void setUsers(UsersAuthenticationType value) {
        this.users = value;
    }

    /**
     * Gets the value of the plugIn property.
     * 
     * @return
     *     possible object is
     *     {@link PlugInAuthType }
     *     
     */
    public PlugInAuthType getPlugIn() {
        return plugIn;
    }

    /**
     * Sets the value of the plugIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlugInAuthType }
     *     
     */
    public void setPlugIn(PlugInAuthType value) {
        this.plugIn = value;
    }

}
