//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration defining how to load the authorization information for the authenticated user.
 * 
 *                 After a user has been authenticated additional information such as roles can be loaded and
 *                 associated with the user for subsequent authorization checks, this type is used to define
 *                 how the roles are loaded.
 *             
 * 
 * <p>Java class for authorizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="properties" type="{urn:jboss:domain:1.4}propertiesFileType" minOccurs="0"/>
 *         &lt;element name="plug-in" type="{urn:jboss:domain:1.4}plug-inAuthType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorizationType", propOrder = {
    "properties",
    "plugIn"
})
public class AuthorizationType {

    protected PropertiesFileType properties;
    @XmlElement(name = "plug-in")
    protected PlugInAuthType plugIn;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesFileType }
     *     
     */
    public PropertiesFileType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesFileType }
     *     
     */
    public void setProperties(PropertiesFileType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the plugIn property.
     * 
     * @return
     *     possible object is
     *     {@link PlugInAuthType }
     *     
     */
    public PlugInAuthType getPlugIn() {
        return plugIn;
    }

    /**
     * Sets the value of the plugIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlugInAuthType }
     *     
     */
    public void setPlugIn(PlugInAuthType value) {
        this.plugIn = value;
    }

}
