//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clustersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clustersType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}server-groupType">
 *       &lt;sequence>
 *         &lt;element name="partition-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state-transfer-timeout" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="method-call-timeout" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="category" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clustersType", propOrder = {
    "partitionName",
    "stateTransferTimeout",
    "methodCallTimeout"
})
public class ClustersType
    extends ServerGroupType
{

    @XmlElement(name = "partition-name", required = true)
    protected String partitionName;
    @XmlElement(name = "state-transfer-timeout", required = true)
    protected BigInteger stateTransferTimeout;
    @XmlElement(name = "method-call-timeout", required = true)
    protected BigInteger methodCallTimeout;
    @XmlAttribute(required = true)
    protected String category;

    /**
     * Gets the value of the partitionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitionName() {
        return partitionName;
    }

    /**
     * Sets the value of the partitionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitionName(String value) {
        this.partitionName = value;
    }

    /**
     * Gets the value of the stateTransferTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStateTransferTimeout() {
        return stateTransferTimeout;
    }

    /**
     * Sets the value of the stateTransferTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStateTransferTimeout(BigInteger value) {
        this.stateTransferTimeout = value;
    }

    /**
     * Gets the value of the methodCallTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMethodCallTimeout() {
        return methodCallTimeout;
    }

    /**
     * Sets the value of the methodCallTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMethodCallTimeout(BigInteger value) {
        this.methodCallTimeout = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
