//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domain-controllerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domain-controllerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="local" type="{urn:jboss:domain:1.4}domain-controller-localType"/>
 *         &lt;element name="remote" type="{urn:jboss:domain:1.4}domain-controller-remoteType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain-controllerType", propOrder = {
    "local",
    "remote"
})
public class DomainControllerType {

    protected DomainControllerLocalType local;
    protected DomainControllerRemoteType remote;

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link DomainControllerLocalType }
     *     
     */
    public DomainControllerLocalType getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainControllerLocalType }
     *     
     */
    public void setLocal(DomainControllerLocalType value) {
        this.local = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link DomainControllerRemoteType }
     *     
     */
    public DomainControllerRemoteType getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainControllerRemoteType }
     *     
     */
    public void setRemote(DomainControllerRemoteType value) {
        this.remote = value;
    }

}
