//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Domain-wide default configuration settings for the management of standalone servers and a Host Controller.
 *             
 * 
 * <p>Java class for domain-managementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domain-managementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="security-realms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="security-realm" type="{urn:jboss:domain:1.4}security-realmType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="outbound-connections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ldap" type="{urn:jboss:domain:1.4}ldapType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain-managementType", propOrder = {
    "securityRealms",
    "outboundConnections"
})
@XmlSeeAlso({
    HostManagementType.class,
    ServerManagementType.class
})
public class DomainManagementType {

    @XmlElement(name = "security-realms")
    protected DomainManagementType.SecurityRealms securityRealms;
    @XmlElement(name = "outbound-connections")
    protected DomainManagementType.OutboundConnections outboundConnections;

    /**
     * Gets the value of the securityRealms property.
     * 
     * @return
     *     possible object is
     *     {@link DomainManagementType.SecurityRealms }
     *     
     */
    public DomainManagementType.SecurityRealms getSecurityRealms() {
        return securityRealms;
    }

    /**
     * Sets the value of the securityRealms property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainManagementType.SecurityRealms }
     *     
     */
    public void setSecurityRealms(DomainManagementType.SecurityRealms value) {
        this.securityRealms = value;
    }

    /**
     * Gets the value of the outboundConnections property.
     * 
     * @return
     *     possible object is
     *     {@link DomainManagementType.OutboundConnections }
     *     
     */
    public DomainManagementType.OutboundConnections getOutboundConnections() {
        return outboundConnections;
    }

    /**
     * Sets the value of the outboundConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainManagementType.OutboundConnections }
     *     
     */
    public void setOutboundConnections(DomainManagementType.OutboundConnections value) {
        this.outboundConnections = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ldap" type="{urn:jboss:domain:1.4}ldapType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ldap"
    })
    public static class OutboundConnections {

        @XmlElement(required = true)
        protected LdapType ldap;

        /**
         * Gets the value of the ldap property.
         * 
         * @return
         *     possible object is
         *     {@link LdapType }
         *     
         */
        public LdapType getLdap() {
            return ldap;
        }

        /**
         * Sets the value of the ldap property.
         * 
         * @param value
         *     allowed object is
         *     {@link LdapType }
         *     
         */
        public void setLdap(LdapType value) {
            this.ldap = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="security-realm" type="{urn:jboss:domain:1.4}security-realmType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "securityRealm"
    })
    public static class SecurityRealms {

        @XmlElement(name = "security-realm", required = true)
        protected List<SecurityRealmType> securityRealm;

        /**
         * Gets the value of the securityRealm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the securityRealm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurityRealm().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SecurityRealmType }
         * 
         * 
         */
        public List<SecurityRealmType> getSecurityRealm() {
            if (securityRealm == null) {
                securityRealm = new ArrayList<SecurityRealmType>();
            }
            return this.securityRealm;
        }

    }

}
