//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extensions" type="{urn:jboss:domain:1.4}extensionsType" minOccurs="0"/>
 *         &lt;element name="system-properties" type="{urn:jboss:domain:1.4}properties-with-boottime" minOccurs="0"/>
 *         &lt;element name="paths" type="{urn:jboss:domain:1.4}named-pathsType" minOccurs="0"/>
 *         &lt;element name="profiles" type="{urn:jboss:domain:1.4}profilesType" minOccurs="0"/>
 *         &lt;element name="interfaces" type="{urn:jboss:domain:1.4}named-interfacesType" minOccurs="0"/>
 *         &lt;element name="socket-binding-groups" type="{urn:jboss:domain:1.4}socket-binding-groupsType" minOccurs="0"/>
 *         &lt;element name="deployments" type="{urn:jboss:domain:1.4}domain-deploymentsType" minOccurs="0"/>
 *         &lt;element name="deployment-overlays" type="{urn:jboss:domain:1.4}domain-deployment-overlaysType" minOccurs="0"/>
 *         &lt;element name="server-groups" type="{urn:jboss:domain:1.4}server-groupsType" minOccurs="0"/>
 *         &lt;element name="management-client-content" type="{urn:jboss:domain:1.4}management-client-contentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Unnamed Domain" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extensions",
    "systemProperties",
    "paths",
    "profiles",
    "interfaces",
    "socketBindingGroups",
    "deployments",
    "deploymentOverlays",
    "serverGroups",
    "managementClientContent"
})
@XmlRootElement(name = "domain")
public class Domain {

    protected ExtensionsType extensions;
    @XmlElement(name = "system-properties")
    protected PropertiesWithBoottime systemProperties;
    protected NamedPathsType paths;
    protected ProfilesType profiles;
    protected NamedInterfacesType interfaces;
    @XmlElement(name = "socket-binding-groups")
    protected SocketBindingGroupsType socketBindingGroups;
    protected DomainDeploymentsType deployments;
    @XmlElement(name = "deployment-overlays")
    protected DomainDeploymentOverlaysType deploymentOverlays;
    @XmlElement(name = "server-groups")
    protected ServerGroupsType serverGroups;
    @XmlElement(name = "management-client-content")
    protected ManagementClientContentType managementClientContent;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsType }
     *     
     */
    public ExtensionsType getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsType }
     *     
     */
    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the systemProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public PropertiesWithBoottime getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public void setSystemProperties(PropertiesWithBoottime value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the paths property.
     * 
     * @return
     *     possible object is
     *     {@link NamedPathsType }
     *     
     */
    public NamedPathsType getPaths() {
        return paths;
    }

    /**
     * Sets the value of the paths property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedPathsType }
     *     
     */
    public void setPaths(NamedPathsType value) {
        this.paths = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link ProfilesType }
     *     
     */
    public ProfilesType getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfilesType }
     *     
     */
    public void setProfiles(ProfilesType value) {
        this.profiles = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link NamedInterfacesType }
     *     
     */
    public NamedInterfacesType getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedInterfacesType }
     *     
     */
    public void setInterfaces(NamedInterfacesType value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the socketBindingGroups property.
     * 
     * @return
     *     possible object is
     *     {@link SocketBindingGroupsType }
     *     
     */
    public SocketBindingGroupsType getSocketBindingGroups() {
        return socketBindingGroups;
    }

    /**
     * Sets the value of the socketBindingGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketBindingGroupsType }
     *     
     */
    public void setSocketBindingGroups(SocketBindingGroupsType value) {
        this.socketBindingGroups = value;
    }

    /**
     * Gets the value of the deployments property.
     * 
     * @return
     *     possible object is
     *     {@link DomainDeploymentsType }
     *     
     */
    public DomainDeploymentsType getDeployments() {
        return deployments;
    }

    /**
     * Sets the value of the deployments property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainDeploymentsType }
     *     
     */
    public void setDeployments(DomainDeploymentsType value) {
        this.deployments = value;
    }

    /**
     * Gets the value of the deploymentOverlays property.
     * 
     * @return
     *     possible object is
     *     {@link DomainDeploymentOverlaysType }
     *     
     */
    public DomainDeploymentOverlaysType getDeploymentOverlays() {
        return deploymentOverlays;
    }

    /**
     * Sets the value of the deploymentOverlays property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainDeploymentOverlaysType }
     *     
     */
    public void setDeploymentOverlays(DomainDeploymentOverlaysType value) {
        this.deploymentOverlays = value;
    }

    /**
     * Gets the value of the serverGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ServerGroupsType }
     *     
     */
    public ServerGroupsType getServerGroups() {
        return serverGroups;
    }

    /**
     * Sets the value of the serverGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerGroupsType }
     *     
     */
    public void setServerGroups(ServerGroupsType value) {
        this.serverGroups = value;
    }

    /**
     * Gets the value of the managementClientContent property.
     * 
     * @return
     *     possible object is
     *     {@link ManagementClientContentType }
     *     
     */
    public ManagementClientContentType getManagementClientContent() {
        return managementClientContent;
    }

    /**
     * Sets the value of the managementClientContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagementClientContentType }
     *     
     */
    public void setManagementClientContent(ManagementClientContentType value) {
        this.managementClientContent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Unnamed Domain";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
