//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of a host's exposed HTTP management interface.
 *             
 * 
 * <p>Java class for host-http-management-interfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="host-http-management-interfaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}management-interfaceType">
 *       &lt;sequence>
 *         &lt;element name="socket" type="{urn:jboss:domain:1.4}http-management-socketType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="console-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "host-http-management-interfaceType", propOrder = {
    "socket"
})
public class HostHttpManagementInterfaceType
    extends ManagementInterfaceType
{

    @XmlElement(required = true)
    protected HttpManagementSocketType socket;
    @XmlAttribute(name = "console-enabled")
    protected Boolean consoleEnabled;

    /**
     * Gets the value of the socket property.
     * 
     * @return
     *     possible object is
     *     {@link HttpManagementSocketType }
     *     
     */
    public HttpManagementSocketType getSocket() {
        return socket;
    }

    /**
     * Sets the value of the socket property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpManagementSocketType }
     *     
     */
    public void setSocket(HttpManagementSocketType value) {
        this.socket = value;
    }

    /**
     * Gets the value of the consoleEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConsoleEnabled() {
        if (consoleEnabled == null) {
            return true;
        } else {
            return consoleEnabled;
        }
    }

    /**
     * Sets the value of the consoleEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConsoleEnabled(Boolean value) {
        this.consoleEnabled = value;
    }

}
