//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The centralized configuration for the management of a Host Controller.
 *             
 * 
 * <p>Java class for host-managementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="host-managementType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}domain-managementType">
 *       &lt;sequence>
 *         &lt;element name="management-interfaces" type="{urn:jboss:domain:1.4}host-management-interfacesType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "host-managementType", propOrder = {
    "managementInterfaces"
})
public class HostManagementType
    extends DomainManagementType
{

    @XmlElement(name = "management-interfaces", required = true)
    protected HostManagementInterfacesType managementInterfaces;

    /**
     * Gets the value of the managementInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link HostManagementInterfacesType }
     *     
     */
    public HostManagementInterfacesType getManagementInterfaces() {
        return managementInterfaces;
    }

    /**
     * Sets the value of the managementInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostManagementInterfacesType }
     *     
     */
    public void setManagementInterfaces(HostManagementInterfacesType value) {
        this.managementInterfaces = value;
    }

}
