//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Reference to the configurations of the sockets to be used by a standalone server's exposed HTTP and HTTPS management interface.
 *             
 * 
 * <p>Java class for http-management-socket-binding-refType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="http-management-socket-binding-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="http" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="https" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "http-management-socket-binding-refType")
public class HttpManagementSocketBindingRefType {

    @XmlAttribute
    protected String http;
    @XmlAttribute
    protected String https;

    /**
     * Gets the value of the http property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttp() {
        return http;
    }

    /**
     * Sets the value of the http property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttp(String value) {
        this.http = value;
    }

    /**
     * Gets the value of the https property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttps() {
        return https;
    }

    /**
     * Sets the value of the https property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttps(String value) {
        this.https = value;
    }

}
