//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for jvmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jvmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="heap" type="{urn:jboss:domain:1.4}heapType" minOccurs="0"/>
 *         &lt;element name="permgen" type="{urn:jboss:domain:1.4}bounded-memory-sizeType" minOccurs="0"/>
 *         &lt;element name="stack" type="{urn:jboss:domain:1.4}memory-sizeType" minOccurs="0"/>
 *         &lt;element name="agent-lib" type="{urn:jboss:domain:1.4}jvm-agentLibType" minOccurs="0"/>
 *         &lt;element name="agent-path" type="{urn:jboss:domain:1.4}jvm-agentPathType" minOccurs="0"/>
 *         &lt;element name="java-agent" type="{urn:jboss:domain:1.4}jvm-javaagentType" minOccurs="0"/>
 *         &lt;element name="jvm-options" type="{urn:jboss:domain:1.4}jvm-optionsType" minOccurs="0"/>
 *         &lt;element name="environment-variables" type="{urn:jboss:domain:1.4}environmentVariablesType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="java-home" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" default="SUN">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="SUN"/>
 *             &lt;enumeration value="IBM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="env-classpath-ignored" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jvmType", propOrder = {

})
@XmlSeeAlso({
    NamedJvmType.class
})
public class JvmType {

    protected HeapType heap;
    protected BoundedMemorySizeType permgen;
    protected MemorySizeType stack;
    @XmlElement(name = "agent-lib")
    protected JvmAgentLibType agentLib;
    @XmlElement(name = "agent-path")
    protected JvmAgentPathType agentPath;
    @XmlElement(name = "java-agent")
    protected JvmJavaagentType javaAgent;
    @XmlElement(name = "jvm-options")
    protected JvmOptionsType jvmOptions;
    @XmlElement(name = "environment-variables")
    protected EnvironmentVariablesType environmentVariables;
    @XmlAttribute(name = "java-home")
    protected String javaHome;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "env-classpath-ignored")
    protected Boolean envClasspathIgnored;

    /**
     * Gets the value of the heap property.
     * 
     * @return
     *     possible object is
     *     {@link HeapType }
     *     
     */
    public HeapType getHeap() {
        return heap;
    }

    /**
     * Sets the value of the heap property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeapType }
     *     
     */
    public void setHeap(HeapType value) {
        this.heap = value;
    }

    /**
     * Gets the value of the permgen property.
     * 
     * @return
     *     possible object is
     *     {@link BoundedMemorySizeType }
     *     
     */
    public BoundedMemorySizeType getPermgen() {
        return permgen;
    }

    /**
     * Sets the value of the permgen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoundedMemorySizeType }
     *     
     */
    public void setPermgen(BoundedMemorySizeType value) {
        this.permgen = value;
    }

    /**
     * Gets the value of the stack property.
     * 
     * @return
     *     possible object is
     *     {@link MemorySizeType }
     *     
     */
    public MemorySizeType getStack() {
        return stack;
    }

    /**
     * Sets the value of the stack property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemorySizeType }
     *     
     */
    public void setStack(MemorySizeType value) {
        this.stack = value;
    }

    /**
     * Gets the value of the agentLib property.
     * 
     * @return
     *     possible object is
     *     {@link JvmAgentLibType }
     *     
     */
    public JvmAgentLibType getAgentLib() {
        return agentLib;
    }

    /**
     * Sets the value of the agentLib property.
     * 
     * @param value
     *     allowed object is
     *     {@link JvmAgentLibType }
     *     
     */
    public void setAgentLib(JvmAgentLibType value) {
        this.agentLib = value;
    }

    /**
     * Gets the value of the agentPath property.
     * 
     * @return
     *     possible object is
     *     {@link JvmAgentPathType }
     *     
     */
    public JvmAgentPathType getAgentPath() {
        return agentPath;
    }

    /**
     * Sets the value of the agentPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link JvmAgentPathType }
     *     
     */
    public void setAgentPath(JvmAgentPathType value) {
        this.agentPath = value;
    }

    /**
     * Gets the value of the javaAgent property.
     * 
     * @return
     *     possible object is
     *     {@link JvmJavaagentType }
     *     
     */
    public JvmJavaagentType getJavaAgent() {
        return javaAgent;
    }

    /**
     * Sets the value of the javaAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JvmJavaagentType }
     *     
     */
    public void setJavaAgent(JvmJavaagentType value) {
        this.javaAgent = value;
    }

    /**
     * Gets the value of the jvmOptions property.
     * 
     * @return
     *     possible object is
     *     {@link JvmOptionsType }
     *     
     */
    public JvmOptionsType getJvmOptions() {
        return jvmOptions;
    }

    /**
     * Sets the value of the jvmOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JvmOptionsType }
     *     
     */
    public void setJvmOptions(JvmOptionsType value) {
        this.jvmOptions = value;
    }

    /**
     * Gets the value of the environmentVariables property.
     * 
     * @return
     *     possible object is
     *     {@link EnvironmentVariablesType }
     *     
     */
    public EnvironmentVariablesType getEnvironmentVariables() {
        return environmentVariables;
    }

    /**
     * Sets the value of the environmentVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvironmentVariablesType }
     *     
     */
    public void setEnvironmentVariables(EnvironmentVariablesType value) {
        this.environmentVariables = value;
    }

    /**
     * Gets the value of the javaHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaHome() {
        return javaHome;
    }

    /**
     * Sets the value of the javaHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaHome(String value) {
        this.javaHome = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "SUN";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the envClasspathIgnored property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnvClasspathIgnored() {
        if (envClasspathIgnored == null) {
            return true;
        } else {
            return envClasspathIgnored;
        }
    }

    /**
     * Sets the value of the envClasspathIgnored property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnvClasspathIgnored(Boolean value) {
        this.envClasspathIgnored = value;
    }

}
