//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Definition to use LDAP as the user repository.
 *             
 * 
 * <p>Java class for ldapAuthenticationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ldapAuthenticationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="username-filter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="advanced-filter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="filter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="connection" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="base-dn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="recursive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="user-dn" type="{http://www.w3.org/2001/XMLSchema}string" default="dn" />
 *       &lt;attribute name="allow-empty-passwords" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldapAuthenticationType", propOrder = {
    "usernameFilter",
    "advancedFilter"
})
public class LdapAuthenticationType {

    @XmlElement(name = "username-filter")
    protected LdapAuthenticationType.UsernameFilter usernameFilter;
    @XmlElement(name = "advanced-filter")
    protected LdapAuthenticationType.AdvancedFilter advancedFilter;
    @XmlAttribute(required = true)
    protected String connection;
    @XmlAttribute(name = "base-dn", required = true)
    protected String baseDn;
    @XmlAttribute
    protected Boolean recursive;
    @XmlAttribute(name = "user-dn")
    protected String userDn;
    @XmlAttribute(name = "allow-empty-passwords")
    protected Boolean allowEmptyPasswords;

    /**
     * Gets the value of the usernameFilter property.
     * 
     * @return
     *     possible object is
     *     {@link LdapAuthenticationType.UsernameFilter }
     *     
     */
    public LdapAuthenticationType.UsernameFilter getUsernameFilter() {
        return usernameFilter;
    }

    /**
     * Sets the value of the usernameFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapAuthenticationType.UsernameFilter }
     *     
     */
    public void setUsernameFilter(LdapAuthenticationType.UsernameFilter value) {
        this.usernameFilter = value;
    }

    /**
     * Gets the value of the advancedFilter property.
     * 
     * @return
     *     possible object is
     *     {@link LdapAuthenticationType.AdvancedFilter }
     *     
     */
    public LdapAuthenticationType.AdvancedFilter getAdvancedFilter() {
        return advancedFilter;
    }

    /**
     * Sets the value of the advancedFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapAuthenticationType.AdvancedFilter }
     *     
     */
    public void setAdvancedFilter(LdapAuthenticationType.AdvancedFilter value) {
        this.advancedFilter = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnection(String value) {
        this.connection = value;
    }

    /**
     * Gets the value of the baseDn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDn() {
        return baseDn;
    }

    /**
     * Sets the value of the baseDn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDn(String value) {
        this.baseDn = value;
    }

    /**
     * Gets the value of the recursive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRecursive() {
        if (recursive == null) {
            return false;
        } else {
            return recursive;
        }
    }

    /**
     * Sets the value of the recursive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecursive(Boolean value) {
        this.recursive = value;
    }

    /**
     * Gets the value of the userDn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDn() {
        if (userDn == null) {
            return "dn";
        } else {
            return userDn;
        }
    }

    /**
     * Sets the value of the userDn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDn(String value) {
        this.userDn = value;
    }

    /**
     * Gets the value of the allowEmptyPasswords property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowEmptyPasswords() {
        if (allowEmptyPasswords == null) {
            return false;
        } else {
            return allowEmptyPasswords;
        }
    }

    /**
     * Sets the value of the allowEmptyPasswords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowEmptyPasswords(Boolean value) {
        this.allowEmptyPasswords = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="filter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdvancedFilter {

        @XmlAttribute(required = true)
        protected String filter;

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilter(String value) {
            this.filter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsernameFilter {

        @XmlAttribute(required = true)
        protected String attribute;

        /**
         * Gets the value of the attribute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttribute() {
            return attribute;
        }

        /**
         * Sets the value of the attribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttribute(String value) {
            this.attribute = value;
        }

    }

}
