//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 *                    Storage information about re-usable chunks of data useful to management clients that are stored
 *                    in the domain content repository.
 *                 
 *             
 * 
 * <p>Java class for management-client-contentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="management-client-contentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rollout-plans" type="{urn:jboss:domain:1.4}contentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "management-client-contentType", propOrder = {
    "rolloutPlans"
})
public class ManagementClientContentType {

    @XmlElement(name = "rollout-plans")
    protected ContentType rolloutPlans;

    /**
     * Gets the value of the rolloutPlans property.
     * 
     * @return
     *     possible object is
     *     {@link ContentType }
     *     
     */
    public ContentType getRolloutPlans() {
        return rolloutPlans;
    }

    /**
     * Sets the value of the rolloutPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentType }
     *     
     */
    public void setRolloutPlans(ContentType value) {
        this.rolloutPlans = value;
    }

}
