//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Declaration of users stored within properties files.
 * 
 *                 The entries within the properties file are username={credentials} with each user
 *                 being specified on it's own line.
 *             
 * 
 * <p>Java class for propertiesAuthenticationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertiesAuthenticationType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}propertiesFileType">
 *       &lt;attribute name="plain-text" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesAuthenticationType")
public class PropertiesAuthenticationType
    extends PropertiesFileType
{

    @XmlAttribute(name = "plain-text")
    protected Boolean plainText;

    /**
     * Gets the value of the plainText property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPlainText() {
        if (plainText == null) {
            return false;
        } else {
            return plainText;
        }
    }

    /**
     * Sets the value of the plainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlainText(Boolean value) {
        this.plainText = value;
    }

}
