//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of a security realm for securing access to the management interfaces.
 *             
 * 
 * <p>Java class for security-realmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="security-realmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plug-ins" type="{urn:jboss:domain:1.4}plug-insType" minOccurs="0"/>
 *         &lt;element name="server-identities" type="{urn:jboss:domain:1.4}server-identitiesType" minOccurs="0"/>
 *         &lt;element name="authentication" type="{urn:jboss:domain:1.4}authenticationType" minOccurs="0"/>
 *         &lt;element name="authorization" type="{urn:jboss:domain:1.4}authorizationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "security-realmType", propOrder = {
    "plugIns",
    "serverIdentities",
    "authentication",
    "authorization"
})
public class SecurityRealmType {

    @XmlElement(name = "plug-ins")
    protected PlugInsType plugIns;
    @XmlElement(name = "server-identities")
    protected ServerIdentitiesType serverIdentities;
    protected AuthenticationType authentication;
    protected AuthorizationType authorization;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the plugIns property.
     * 
     * @return
     *     possible object is
     *     {@link PlugInsType }
     *     
     */
    public PlugInsType getPlugIns() {
        return plugIns;
    }

    /**
     * Sets the value of the plugIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlugInsType }
     *     
     */
    public void setPlugIns(PlugInsType value) {
        this.plugIns = value;
    }

    /**
     * Gets the value of the serverIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link ServerIdentitiesType }
     *     
     */
    public ServerIdentitiesType getServerIdentities() {
        return serverIdentities;
    }

    /**
     * Sets the value of the serverIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerIdentitiesType }
     *     
     */
    public void setServerIdentities(ServerIdentitiesType value) {
        this.serverIdentities = value;
    }

    /**
     * Gets the value of the authentication property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationType }
     *     
     */
    public AuthenticationType getAuthentication() {
        return authentication;
    }

    /**
     * Sets the value of the authentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationType }
     *     
     */
    public void setAuthentication(AuthenticationType value) {
        this.authentication = value;
    }

    /**
     * Gets the value of the authorization property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationType }
     *     
     */
    public AuthorizationType getAuthorization() {
        return authorization;
    }

    /**
     * Sets the value of the authorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationType }
     *     
     */
    public void setAuthorization(AuthorizationType value) {
        this.authorization = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
