//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of a standalone server's exposed HTTP/HTTPS management interface.
 *             
 * 
 * 
 *                         Configuration of the socket to use for the HTTP/HTTPS management interface is a choice
 *                         between a direct configuration of the address and ports, or a reference to socket-binding
 *                         configurations in the server's socket-binding-group element. The latter is the recommended
 *                         approach is it makes it easier to avoid port conflicts by taking advantage of the
 *                         socket-binding-group's port-offset configuration. Direct configuration of the address and
 *                         ports is provided to preserve backward compatibility.
 *                     
 * 
 * <p>Java class for server-http-management-interfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="server-http-management-interfaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}management-interfaceType">
 *       &lt;choice>
 *         &lt;element name="socket" type="{urn:jboss:domain:1.4}http-management-socketType"/>
 *         &lt;element name="socket-binding" type="{urn:jboss:domain:1.4}http-management-socket-binding-refType"/>
 *       &lt;/choice>
 *       &lt;attribute name="console-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "server-http-management-interfaceType", propOrder = {
    "socket",
    "socketBinding"
})
public class ServerHttpManagementInterfaceType
    extends ManagementInterfaceType
{

    protected HttpManagementSocketType socket;
    @XmlElement(name = "socket-binding")
    protected HttpManagementSocketBindingRefType socketBinding;
    @XmlAttribute(name = "console-enabled")
    protected Boolean consoleEnabled;

    /**
     * Gets the value of the socket property.
     * 
     * @return
     *     possible object is
     *     {@link HttpManagementSocketType }
     *     
     */
    public HttpManagementSocketType getSocket() {
        return socket;
    }

    /**
     * Sets the value of the socket property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpManagementSocketType }
     *     
     */
    public void setSocket(HttpManagementSocketType value) {
        this.socket = value;
    }

    /**
     * Gets the value of the socketBinding property.
     * 
     * @return
     *     possible object is
     *     {@link HttpManagementSocketBindingRefType }
     *     
     */
    public HttpManagementSocketBindingRefType getSocketBinding() {
        return socketBinding;
    }

    /**
     * Sets the value of the socketBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpManagementSocketBindingRefType }
     *     
     */
    public void setSocketBinding(HttpManagementSocketBindingRefType value) {
        this.socketBinding = value;
    }

    /**
     * Gets the value of the consoleEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConsoleEnabled() {
        if (consoleEnabled == null) {
            return true;
        } else {
            return consoleEnabled;
        }
    }

    /**
     * Sets the value of the consoleEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConsoleEnabled(Boolean value) {
        this.consoleEnabled = value;
    }

}
