//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of the identities that represent the server.
 *             
 * 
 * <p>Java class for server-identitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="server-identitiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ssl" type="{urn:jboss:domain:1.4}sslType" minOccurs="0"/>
 *         &lt;element name="secret" type="{urn:jboss:domain:1.4}secretType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "server-identitiesType", propOrder = {
    "ssl",
    "secret"
})
public class ServerIdentitiesType {

    protected SslType ssl;
    protected SecretType secret;

    /**
     * Gets the value of the ssl property.
     * 
     * @return
     *     possible object is
     *     {@link SslType }
     *     
     */
    public SslType getSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SslType }
     *     
     */
    public void setSsl(SslType value) {
        this.ssl = value;
    }

    /**
     * Gets the value of the secret property.
     * 
     * @return
     *     possible object is
     *     {@link SecretType }
     *     
     */
    public SecretType getSecret() {
        return secret;
    }

    /**
     * Sets the value of the secret property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecretType }
     *     
     */
    public void setSecret(SecretType value) {
        this.secret = value;
    }

}
