//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serverType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="paths" type="{urn:jboss:domain:1.4}specified-pathsType" minOccurs="0"/>
 *         &lt;element name="interfaces" type="{urn:jboss:domain:1.4}specified-interfacesType" minOccurs="0"/>
 *         &lt;element name="socket-bindings" type="{urn:jboss:domain:1.4}server-socket-bindingsType" minOccurs="0"/>
 *         &lt;element name="system-properties" type="{urn:jboss:domain:1.4}properties-with-boottime" minOccurs="0"/>
 *         &lt;element name="jvm" type="{urn:jboss:domain:1.4}serverJvmType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="auto-start" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serverType", propOrder = {

})
public class ServerType {

    protected SpecifiedPathsType paths;
    protected SpecifiedInterfacesType interfaces;
    @XmlElement(name = "socket-bindings")
    protected ServerSocketBindingsType socketBindings;
    @XmlElement(name = "system-properties")
    protected PropertiesWithBoottime systemProperties;
    protected ServerJvmType jvm;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String group;
    @XmlAttribute(name = "auto-start")
    protected Boolean autoStart;

    /**
     * Gets the value of the paths property.
     * 
     * @return
     *     possible object is
     *     {@link SpecifiedPathsType }
     *     
     */
    public SpecifiedPathsType getPaths() {
        return paths;
    }

    /**
     * Sets the value of the paths property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecifiedPathsType }
     *     
     */
    public void setPaths(SpecifiedPathsType value) {
        this.paths = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link SpecifiedInterfacesType }
     *     
     */
    public SpecifiedInterfacesType getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecifiedInterfacesType }
     *     
     */
    public void setInterfaces(SpecifiedInterfacesType value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the socketBindings property.
     * 
     * @return
     *     possible object is
     *     {@link ServerSocketBindingsType }
     *     
     */
    public ServerSocketBindingsType getSocketBindings() {
        return socketBindings;
    }

    /**
     * Sets the value of the socketBindings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerSocketBindingsType }
     *     
     */
    public void setSocketBindings(ServerSocketBindingsType value) {
        this.socketBindings = value;
    }

    /**
     * Gets the value of the systemProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public PropertiesWithBoottime getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public void setSystemProperties(PropertiesWithBoottime value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the jvm property.
     * 
     * @return
     *     possible object is
     *     {@link ServerJvmType }
     *     
     */
    public ServerJvmType getJvm() {
        return jvm;
    }

    /**
     * Sets the value of the jvm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerJvmType }
     *     
     */
    public void setJvm(ServerJvmType value) {
        this.jvm = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the autoStart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoStart() {
        if (autoStart == null) {
            return true;
        } else {
            return autoStart;
        }
    }

    /**
     * Sets the value of the autoStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoStart(Boolean value) {
        this.autoStart = value;
    }

}
