//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of the socket used by host or standalone server's exposed HTTP management interface.
 *             
 * 
 * 
 *                         Configuration of the socket to use for the native management interface is a choice
 *                         between a direct configuration of the address and port, or a reference to a socket-binding
 *                         configuration in the server's socket-binding-group element. The latter is the recommended
 *                         approach is it makes it easier to avoid port conflicts by taking advantage of the
 *                         socket-binding-group's port-offset configuration. Direct configuration of the address and
 *                         ports is provided to preserve backward compatibility.
 *                     
 * 
 * <p>Java class for server-native-management-interfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="server-native-management-interfaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:jboss:domain:1.4}management-interfaceType">
 *       &lt;choice>
 *         &lt;element name="socket" type="{urn:jboss:domain:1.4}native-management-socketType"/>
 *         &lt;element name="socket-binding" type="{urn:jboss:domain:1.4}native-management-socket-binding-refType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "server-native-management-interfaceType", propOrder = {
    "socket",
    "socketBinding"
})
public class ServerNativeManagementInterfaceType
    extends ManagementInterfaceType
{

    protected NativeManagementSocketType socket;
    @XmlElement(name = "socket-binding")
    protected NativeManagementSocketBindingRefType socketBinding;

    /**
     * Gets the value of the socket property.
     * 
     * @return
     *     possible object is
     *     {@link NativeManagementSocketType }
     *     
     */
    public NativeManagementSocketType getSocket() {
        return socket;
    }

    /**
     * Sets the value of the socket property.
     * 
     * @param value
     *     allowed object is
     *     {@link NativeManagementSocketType }
     *     
     */
    public void setSocket(NativeManagementSocketType value) {
        this.socket = value;
    }

    /**
     * Gets the value of the socketBinding property.
     * 
     * @return
     *     possible object is
     *     {@link NativeManagementSocketBindingRefType }
     *     
     */
    public NativeManagementSocketBindingRefType getSocketBinding() {
        return socketBinding;
    }

    /**
     * Sets the value of the socketBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link NativeManagementSocketBindingRefType }
     *     
     */
    public void setSocketBinding(NativeManagementSocketBindingRefType value) {
        this.socketBinding = value;
    }

}
