//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for server-groupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="server-groupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jvm" type="{urn:jboss:domain:1.4}namedJvmType" minOccurs="0"/>
 *         &lt;element name="socket-binding-group" type="{urn:jboss:domain:1.4}socket-binding-group-refType"/>
 *         &lt;element name="deployments" type="{urn:jboss:domain:1.4}server-groupDeploymentsType" minOccurs="0"/>
 *         &lt;element name="deployment-overlays" type="{urn:jboss:domain:1.4}server-group-deployment-overlaysType" minOccurs="0"/>
 *         &lt;element name="system-properties" type="{urn:jboss:domain:1.4}properties-with-boottime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="management-subsystem-endpoint" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "server-groupType", propOrder = {
    "jvm",
    "socketBindingGroup",
    "deployments",
    "deploymentOverlays",
    "systemProperties"
})
@XmlSeeAlso({
    ClustersType.class
})
public class ServerGroupType {

    protected NamedJvmType jvm;
    @XmlElement(name = "socket-binding-group", required = true)
    protected SocketBindingGroupRefType socketBindingGroup;
    protected ServerGroupDeploymentsType deployments;
    @XmlElement(name = "deployment-overlays")
    protected ServerGroupDeploymentOverlaysType deploymentOverlays;
    @XmlElement(name = "system-properties")
    protected PropertiesWithBoottime systemProperties;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String profile;
    @XmlAttribute(name = "management-subsystem-endpoint")
    protected Boolean managementSubsystemEndpoint;

    /**
     * Gets the value of the jvm property.
     * 
     * @return
     *     possible object is
     *     {@link NamedJvmType }
     *     
     */
    public NamedJvmType getJvm() {
        return jvm;
    }

    /**
     * Sets the value of the jvm property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedJvmType }
     *     
     */
    public void setJvm(NamedJvmType value) {
        this.jvm = value;
    }

    /**
     * Gets the value of the socketBindingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link SocketBindingGroupRefType }
     *     
     */
    public SocketBindingGroupRefType getSocketBindingGroup() {
        return socketBindingGroup;
    }

    /**
     * Sets the value of the socketBindingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketBindingGroupRefType }
     *     
     */
    public void setSocketBindingGroup(SocketBindingGroupRefType value) {
        this.socketBindingGroup = value;
    }

    /**
     * Gets the value of the deployments property.
     * 
     * @return
     *     possible object is
     *     {@link ServerGroupDeploymentsType }
     *     
     */
    public ServerGroupDeploymentsType getDeployments() {
        return deployments;
    }

    /**
     * Sets the value of the deployments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerGroupDeploymentsType }
     *     
     */
    public void setDeployments(ServerGroupDeploymentsType value) {
        this.deployments = value;
    }

    /**
     * Gets the value of the deploymentOverlays property.
     * 
     * @return
     *     possible object is
     *     {@link ServerGroupDeploymentOverlaysType }
     *     
     */
    public ServerGroupDeploymentOverlaysType getDeploymentOverlays() {
        return deploymentOverlays;
    }

    /**
     * Sets the value of the deploymentOverlays property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerGroupDeploymentOverlaysType }
     *     
     */
    public void setDeploymentOverlays(ServerGroupDeploymentOverlaysType value) {
        this.deploymentOverlays = value;
    }

    /**
     * Gets the value of the systemProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public PropertiesWithBoottime getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesWithBoottime }
     *     
     */
    public void setSystemProperties(PropertiesWithBoottime value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfile(String value) {
        this.profile = value;
    }

    /**
     * Gets the value of the managementSubsystemEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isManagementSubsystemEndpoint() {
        if (managementSubsystemEndpoint == null) {
            return false;
        } else {
            return managementSubsystemEndpoint;
        }
    }

    /**
     * Sets the value of the managementSubsystemEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setManagementSubsystemEndpoint(Boolean value) {
        this.managementSubsystemEndpoint = value;
    }

}
