//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             
 *                 Server-specific overrides to the default socket binding configuration inherited from the server group.
 *             
 *             
 * 
 * <p>Java class for server-socket-bindingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="server-socket-bindingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="socket-binding-group" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="port-offset" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "server-socket-bindingsType")
public class ServerSocketBindingsType {

    @XmlAttribute(name = "socket-binding-group")
    protected String socketBindingGroup;
    @XmlAttribute(name = "port-offset")
    protected Integer portOffset;

    /**
     * Gets the value of the socketBindingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocketBindingGroup() {
        return socketBindingGroup;
    }

    /**
     * Sets the value of the socketBindingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocketBindingGroup(String value) {
        this.socketBindingGroup = value;
    }

    /**
     * Gets the value of the portOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPortOffset() {
        if (portOffset == null) {
            return  0;
        } else {
            return portOffset;
        }
    }

    /**
     * Sets the value of the portOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPortOffset(Integer value) {
        this.portOffset = value;
    }

}
