//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 01:55:54 PM PDT 
//


package org.jboss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration of the SSL identity of this server.
 *             
 * 
 * <p>Java class for sslType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sslType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keystore" type="{urn:jboss:domain:1.4}extendedKeyStoreType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" default="TLS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sslType", propOrder = {
    "keystore"
})
public class SslType {

    @XmlElement(required = true)
    protected ExtendedKeyStoreType keystore;
    @XmlAttribute
    protected String protocol;

    /**
     * Gets the value of the keystore property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedKeyStoreType }
     *     
     */
    public ExtendedKeyStoreType getKeystore() {
        return keystore;
    }

    /**
     * Sets the value of the keystore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedKeyStoreType }
     *     
     */
    public void setKeystore(ExtendedKeyStoreType value) {
        this.keystore = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        if (protocol == null) {
            return "TLS";
        } else {
            return protocol;
        }
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

}
